# Deployment Configuration

# Helm Repositories to add
helm_repositories:
  - name: aws-cloud-controller-manager
    url: https://kubernetes.github.io/cloud-provider-aws
  - name: aws-ebs-csi-driver
    url: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
  # - name: wiremind
  #   url: https://wiremind.github.io/wiremind-helm-charts

# Helm Templates to generate
helm_templates:
  - name: aws-cloud-controller-manager
    chart: aws-cloud-controller-manager/aws-cloud-controller-manager
    namespace: kube-system
    output: k8s/manifests/aws-ccm.yaml
    values:
      hostNetwork: true
      hostNetworking: true
      "args[0]": "--v=2"
      "args[1]": "--cloud-provider=aws"
      "args[2]": "--cluster-name=kubernetes"
      "args[3]": "--allocate-node-cidrs=true"
      "args[4]": "--cluster-cidr=${POD_CIDR}"
      "args[5]": "--configure-cloud-routes=false"

  - name: aws-ebs-csi-driver
    chart: aws-ebs-csi-driver/aws-ebs-csi-driver
    namespace: kube-system
    output: k8s/manifests/aws-ebs-csi.yaml

  # - name: gateway-api-crds
  #   chart: wiremind/gateway-api-crds
  #   version: "1.5.1"
  #   output: k8s/manifests/gateway-api-crds.yaml

  - name: eg
    chart: oci://docker.io/envoyproxy/gateway-helm
    version: v1.8.1
    namespace: envoy-gateway-system
    output: k8s/manifests/envoy-gateway.yaml

# Remote/Static manifests to generate or download
manifests:
  - name: flannel
    url: https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
    output: k8s/manifests/kube-flannel.yaml
    replacements:
      "10.244.0.0/16": "${POD_CIDR}"

  - name: namespaces
    output: k8s/manifests/namespaces.yaml
    content: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: envoy-gateway-system

# Deployment steps to apply, in order
deploy_steps:
  - action: apply
    server_side: true
    files:
      - k8s/manifests/namespaces.yaml

  # - action: apply
  #   server_side: true
  #   files:
  #     - k8s/manifests/gateway-api-crds.yaml

  - action: apply
    files:
      - k8s/manifests/aws-ccm.yaml
      - k8s/manifests/aws-ebs-csi.yaml
      - k8s/manifests/envoy-gateway.yaml

  - action: apply
    files:
      - k8s/envoy-gateway-config.yml
      - k8s/storage_class.yml
      - k8s/valheim.yml

  - action: patch
    resource: ds/aws-cloud-controller-manager
    namespace: kube-system
    patch_data: '{"spec":{"template":{"spec":{"hostNetwork":true}}}}'
    allow_failure: true
