valheim-k8s:
  worldName: "Wraeclast"
  serverName: "vsy-valheim"
  password: "SecretPassword123"

  storage:
    kind: persistentVolumeClaim
    pvc:
      storageClassName: ebs-sc
      size: 10Gi

  serverStorage:
    kind: persistentVolumeClaim
    pvc:
      storageClassName: ebs-sc
      size: 5Gi

  networking:
    serviceType: ClusterIP
    gamePort: 2456
    publishQueryPort: true
