apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-cloud-controller-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://kubernetes.github.io/cloud-provider-aws'
    chart: aws-cloud-controller-manager
    targetRevision: 0.0.11
    helm:
      values: |
        hostNetwork: true
        args:
          - "--v=2"
          - "--cloud-provider=aws"
          - "--cluster-name=kubeworld-cluster"
          - "--allocate-node-cidrs=true"
          - "--cluster-cidr=10.244.0.0/16"
          - "--configure-cloud-routes=false"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
