apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevela
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubevela.github.io/charts
    chart: vela-core
    targetRevision: '1.9.11'
    helm:
      values: |
        admissionWebhooks:
          certManager:
            enabled: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vela-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
