apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: aws-nlb-proxy
  namespace: default
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: LoadBalancer
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: aws-nlb-proxy
    namespace: default
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: valheim-gateway
  namespace: default
spec:
  gatewayClassName: eg
  listeners:
    - name: valheim-udp-2456
      protocol: UDP
      port: 2456
    - name: valheim-udp-2457
      protocol: UDP
      port: 2457
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: valheim-udp-route-2456
  namespace: default
spec:
  parentRefs:
    - name: valheim-gateway
      sectionName: valheim-udp-2456
  rules:
    - backendRefs:
        - name: valheim-server
          port: 2456
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: valheim-udp-route-2457
  namespace: default
spec:
  parentRefs:
    - name: valheim-gateway
      sectionName: valheim-udp-2457
  rules:
    - backendRefs:
        - name: valheim-server
          port: 2457
