name: Destroy Kubernetes Control Plane Infrastructure

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-southeast-2
  AWS_ROLE_TO_ASSUME: arn:aws:iam::626210706774:role/kube-github-actions-runner

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.x'

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v6.2.0
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Run Pulumi Destroy
        uses: pulumi/actions@v4
        with:
          command: destroy
          stack-name: default
          cloud-url: ${{ secrets.PULUMI_BACKEND_URL }}
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
